file naming confusion

diff --git a/zoom-update b/zoom-update
--- a/zoom-update
+++ b/zoom-update
@@ -1,6 +1,169 @@
 #!/bin/bash
 
-# Resolve the full path of the script
-SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
+if [ "$UID" = "0" ]; then
+  echo "WARNING: Running as root is not recommended!"
+fi
 
-exec "${SCRIPT_DIR}/zoom-update" "--cron"
+[ -f /etc/default/zoom-update ] && . /etc/default/zoom-update
+
+# Set base dir
+ZOOM_CACHE="${ZOOM_CACHE:-${HOME}/zoom}"
+
+ZOOM_REPO="${ZOOM_CACHE}/repo"
+ZOOM_GPG_HOME="${ZOOM_CACHE}/.gnupg"
+ZOOM_GPG_VERIFY=true
+VERSION_FILE="${ZOOM_CACHE}/zoom_deb.version"
+
+# s. https://zoom.us/download?os=linux
+ZOOM_CLIENT_URL="https://zoom.us/client/latest/zoom_amd64.deb"
+#ZOOM_PUBKEY_URL="https://zoom.us/linux/download/pubkey?version=5-12-6"
+#ZOOM_PUBKEY_URL="https://zoom.us/linux/download/pubkey?version=6-3-10"
+#ZOOM_PUBKEY_URL="https://eu02web.zoom.us/linux/download/pubkey?version=6-7-5"
+ZOOM_PUBKEY_URL="https://zoom.us/linux/download/pubkey"
+
+# handle output verbosity
+QUIET=false
+[ "$1" = "--cron" ] && QUIET=true
+#echo "QUIET=${QUIET}"; exit
+
+########################################################################################################################
+# FUNCTIONS
+########################################################################################################################
+
+function purge()
+{
+  rm -rf "${ZOOM_CACHE}"
+}
+
+function init()
+{
+  set -e
+
+  if [ -d "${ZOOM_CACHE}" ]; then
+    ZOOM_CACHE_UID=$(stat -c "%u" "${ZOOM_CACHE}")
+    if [ "$UID" != "$ZOOM_CACHE_UID" ]; then
+      echo "User ID ($UID) and directory owner ($ZOOM_CACHE_UID) do not match - aborting"
+      exit 1
+    fi
+  else
+    echo -n "Initializing directories in ${ZOOM_CACHE}... "
+    mkdir -p "${ZOOM_CACHE}"
+    chmod 751 "${ZOOM_CACHE}"
+
+    mkdir -p "${ZOOM_REPO}"
+    chmod 755 "${ZOOM_REPO}"
+
+    echo "zoom optional default" > "${ZOOM_CACHE}/override"
+    echo "DONE"
+  fi
+
+  # ensure correct GPG home permissions to avoid warning
+  if [ -d "${ZOOM_GPG_HOME}" ]; then
+    find "${ZOOM_GPG_HOME}" -type f -exec chmod 600 {} \; # Set 600 for files
+    find "${ZOOM_GPG_HOME}" -type d -exec chmod 700 {} \; # Set 700 for directories
+  fi
+
+  set +e
+}
+
+function update_latest_zoom_version()
+{
+  $QUIET || echo -n "Updating latest version... "
+  if [ -f "$VERSION_FILE" ]; then
+    OLD_ZOOM_VER=$(tail -n 1 "$VERSION_FILE")
+  else
+    OLD_ZOOM_VER="0.0"
+  fi
+  LATEST_ZOOM_VER=$(wget --spider "${ZOOM_CLIENT_URL}" 2>&1 | grep ^Location: | sed -e 's/.*prod\/\(.*\)\/.*/\1/')
+
+  if [ "x$LATEST_ZOOM_VER" == "x" ]; then
+    echo "ERROR: Unable to determine zoom version"
+    exit 3
+  elif [ ! -f "$VERSION_FILE" ] || ! grep -q "^$LATEST_ZOOM_VER\$" "$VERSION_FILE"; then
+    echo "New version found: $LATEST_ZOOM_VER"
+    echo "$LATEST_ZOOM_VER" >> "$VERSION_FILE"
+  else
+    $QUIET || echo "Version unchanged"
+  fi
+}
+
+function get_pubkey()
+{
+  $QUIET || echo -n "Fetching new GPG key... "
+  wget -q -O "${ZOOM_CACHE}/zoom.key.new" "${ZOOM_PUBKEY_URL}" 2>&1
+  $QUIET || echo "DONE"
+
+  if [ -r "${ZOOM_CACHE}/zoom.key" ]; then
+    if ! cmp -s "${ZOOM_CACHE}/zoom.key.new" "${ZOOM_CACHE}/zoom.key"; then
+      echo "Keys ${ZOOM_CACHE}/{zoom.key|zoom.key.new} differ - aborting"
+      echo "Check keys and if valid remove old one and re-run:"
+      echo "rm ${ZOOM_CACHE}/zoom.key"
+      exit 1
+    fi
+  else
+    echo "Initially importing GPG key"
+    gpg --quiet --homedir "${ZOOM_GPG_HOME}" --import "${ZOOM_CACHE}/zoom.key.new"
+    mv "${ZOOM_CACHE}/zoom.key.new" "${ZOOM_CACHE}/zoom.key"
+  fi
+}
+
+function download_latest_zoom()
+{
+  $QUIET || echo -n "Checking for downloads... "
+  LATEST_ZOOM_VER=$(tail -n 1 "$VERSION_FILE")
+  FILENAME="zoom_${LATEST_ZOOM_VER}_amd64.deb"
+  TARGET_FILE="${ZOOM_REPO}/${FILENAME}"
+  $QUIET || echo "Checking Zoom package file (${TARGET_FILE})"
+  if [ -f "${TARGET_FILE}" ]; then
+    $QUIET || echo "Zoom package file up-to-date (${TARGET_FILE})"
+    if [ -f "${ZOOM_REPO}/Release" ] && grep --silent "${FILENAME}" "${ZOOM_REPO}/Release"; then
+      $QUIET || echo "Zoom repo up-to-date (${ZOOM_REPO})"
+      exit 1 # indicates no error - but also nothing was downloaded and repo does not need to be updated
+    else
+      $QUIET || echo "Zoom repo needs update (${ZOOM_REPO})"
+      exit 0 # already downloaded but repo needs update
+    fi
+  else
+    echo "Found new version (${LATEST_ZOOM_VER})."
+    echo -n "Downloading... "
+    wget --quiet -O "${TARGET_FILE}" "${ZOOM_CLIENT_URL}"
+    echo "DONE"
+
+    if [ "${ZOOM_GPG_VERIFY}" = true ]; then
+      if gpg --quiet --homedir "${ZOOM_GPG_HOME}" --trust-model always --verify "${TARGET_FILE}"; then
+        $QUIET || echo "GPG key check successful for ${TARGET_FILE}"
+      else
+        echo "GPG key check failed for ${TARGET_FILE}"
+        exit 2
+      fi
+    else
+      $QUIET || echo "GPG key check was SKIPPED (see /etc/default/zoom-update)."
+    fi
+
+  fi
+}
+
+function build_repo()
+{
+  echo "Updating repo... "
+  if [ -f "${ZOOM_CACHE}/override" ]; then
+    dpkg-scanpackages --multiversion "${ZOOM_REPO}/" "${ZOOM_CACHE}/override" > "${ZOOM_REPO}/Release"
+  else
+    dpkg-scanpackages --multiversion "${ZOOM_REPO}" > "${ZOOM_REPO}/Release"
+  fi
+  gzip -9c "${ZOOM_REPO}/Release" > "${ZOOM_REPO}/Packages.gz"
+  chmod 644 "${ZOOM_REPO}"/*
+  echo "DONE"
+}
+
+########################################################################################################################
+# DO THE THING ...
+########################################################################################################################
+
+# CAREFUL!
+#purge # use to reset on every start for development
+
+init
+$ZOOM_GPG_VERIFY || get_pubkey
+update_latest_zoom_version
+download_latest_zoom && build_repo
